#!/bin/bash
sudo docker build -t et0803/redis_replica:0.1 .
sudo docker run -d -h redis_replica1 --name redis_replica1 --link redis_primary:redis_primary et0803/redis_replica:0.1
sudo docker run -ti --rm --volumes-from redis_replica1 ubuntu cat /var/log/redis/redis-replica.log
sudo docker run -d -h redis_replica2 --name redis_replica2 --link redis_primary:redis_primary et0803/redis_replica:0.1
sudo docker run -ti --rm --volumes-from redis_replica2 ubuntu cat /var/log/redis/redis-replica.log
