#!/bin/bash
sudo docker build -t et0803/redis_primary:0.1 .
sudo docker run -d -h redis_primary --name redis_primary et0803/redis_primary:0.1
sudo docker logs redis_primary
sudo docker run -ti --rm --volumes-from redis_primary ubuntu cat /var/log/redis/redis-server.log
